name: Deploy Worker
on:
  push:
    branches:
      - master
jobs:
  deploy:
    env:
      apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - name: Build & Deploy Worker
        uses: actions/setup-node@v4
      - run: npm i
      - run: npx wrangler deploy
